SELECT CUSTOMERNUMBER
FROM CLASSICMODELS.CUSTOMERS;

SELECT COUNT(CUSTOMERNUMBER)
FROM CLASSICMODELS.CUSTOMERS;

SELECT SUM(AMOUNT),
COUNT(CHECKNUMBER)
FROM CLASSICMODELS.PAYMENTS;
 
SELECT PRODUCTNAME, PRODUCTLINE
FROM CLASSICMODELS.PRODUCTS;

